name: Prepare deployment artifact
description: Checkout code, setup pnpm and download build artifact

inputs:
  artifact-name:
    description: Name of the artifact to download
    required: true
  unpack-path:
    description: Path to unpack the downloaded artifact
    required: true

runs:
  using: composite
  steps:
    # Setup Node.js and install dependencies
    - uses: Perdolique/automations/.github/actions/setup-pnpm@v1.0.1
      with:
        install-dependencies: true

    # Download build artifact
    - name: Download build artifact
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.unpack-path }}
